### ISSUE TITLE
.slf4j#slf4j-api;1.7.25!slf4j-api.jar downaload Error

### ISSUE THREAD

**Issue by kalita-dhrubajyoti** [ucberkeley-ee290c/fa18-smartnic#3]
sbt "compile; +publishLocal"

Getting this Error:

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] [launcher] download failed: org.slf4j#slf4j-api;1.7.25!slf4j-api.jar
[error] [launcher] error during sbt launcher: error retrieving required libraries

**Comment by nullromo** [comment]
Hi, glad to see you've been checking out the project. Unfortunately this is not a maintained repo. If you are having trouble with the build process, I suggest asking someone familiar with sbt to diagnose the error. At a glance, it looks like [slf4j](https://www.slf4j.org/) could not be downloaded, though we don't use slf4j in the project explicitly. So I suspect this is a toolchain issue likely resulting from `built.sbt` becoming out of date.
